#pragma config(Motor,  motorA,          driveMotLeft,  tmotorEV3_Large, openLoop, driveLeft, encoder)
#pragma config(Motor,  motorB,          driveMotRight, tmotorEV3_Large, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	setMotorSpeed(driveMotLeft, 100.0);
	setMotorSpeed(driveMotRight, 100.0);

	while (true) {


			displayCenteredTextLine(0, "Left RPM: %d", getMotorRPM(driveMotLeft));
			displayCenteredTextLine(1, "Right RPM: %d", getMotorRPM(driveMotRight));

			delay(100);

	}


}
