#pragma config(Motor,  motorC,          handlebarMotor, tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define T (float) 0.01

task main() {

	datalogClear();

	displayCenteredTextLine(0, "Initialising...");
	resetMotorEncoder(handlebarMotor);
	sleep(1000);

	// Main loop
	float dprev = 0.0;

	float time = 0.0;
	clearTimer(T1);
	while (true) {

		float dt = time1[T1] / 1000.0;
		if (dt >= T) {

			clearTimer(T1);

			float u = 100;

			// Set motor
			float error = u - getMotorEncoder(handlebarMotor);

			setMotorSpeed(handlebarMotor, 5 * error);
			dprev = getMotorRPM(handlebarMotor);


			time += dt;

			// Save to datalog
			int scale = 100;
			datalogDataGroupStart();
			datalogAddValue(0, u);
			datalogAddValue(1, getMotorEncoder(handlebarMotor));
			datalogDataGroupEnd();

		}

	}

	datalogClose();

}
